version: '3.8'
volumes:
  mongo-keys:
  mongo-data-0:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:

services:
  mongo-keys:
    image: depop/openssl-bats
    volumes:
      - mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  mongo-primary:
    image: mongo:4.0
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-0:/data/db
    env_file: ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet authapp'
    depends_on:
      - mongo-keys
    networks:
      - authapp

  # Worker 1
  mongo-worker-1:
    image: mongo:4.0
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-1:/data/db
    env_file: ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet authapp'
    depends_on:
      - mongo-keys
    networks:
      - authapp

  # Worker 2
  mongo-worker-2:
    image: mongo:4.0
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-2:/data/db
    env_file: ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet authapp'
    depends_on:
      - mongo-keys
    networks:
      - authapp

  # Worker 3
  mongo-worker-3:
    image: mongo:4.0
    volumes:
      - mongo-keys:/opt/keyfile
      - mongo-data-3:/data/db
    env_file: ./mongod.env
    ports:
      - 27020:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet authapp'
    depends_on:
      - mongo-keys
    networks:
      - authapp
